[workspace]
authors = ["Ondřej Čertík <ondrej@certik.us>"]
channels = ["conda-forge"]
name = "qed"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
start = "myst start"

[dependencies]
mystmd = ">=1.10.1,<2"
